//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICH_VU_TIEN_ICH
    {
        public int ID { get; set; }
        public string MADV { get; set; }
        public string TENDV_VI { get; set; }
        public string TENDV_EN { get; set; }
        public string MOTA_VI { get; set; }
        public string MOTA_EN { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    }
}
