//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhachSan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class qlks_dbEntities : DbContext
    {
        public qlks_dbEntities()
            : base("name=qlks_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DICH_VU_TIEN_ICH> DICH_VU_TIEN_ICH { get; set; }
    
        public virtual ObjectResult<DICH_VU_TIEN_ICH_selectallvi_Result> GetAllDichVu(string maDV)
        {
            var maDVParameter = maDV != null ?
                new ObjectParameter("MaDV", maDV) :
                new ObjectParameter("MaDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DICH_VU_TIEN_ICH_selectallvi_Result>("GetAllDichVu", maDVParameter);
        }
    
        public virtual ObjectResult<DICH_VU_TIEN_ICH_selectonevi_Result> GetOneDichVu(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DICH_VU_TIEN_ICH_selectonevi_Result>("GetOneDichVu", iDParameter);
        }
    }
}
